services:
  - type: web
    name: labshare-connect
    env: python
    buildCommand: |
      # 1. Install Python dependencies
      pip install -r requirements.txt

      # 2. Install frontend dependencies
      cd frontend
      npm install

      # 3. Build frontend directly into backend/static
      npm run build

      # Go back to root for startCommand
      cd ..
    startCommand: gunicorn labshare-connect.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
    plan: free
