services:
  - type: web
    name: labshare-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
      mkdir -p ../backend/static
      cp -r dist/* ../backend/static/
    startCommand: gunicorn app:app
    buildFilter:
      paths:
        - frontend/**
        - backend/**
