services:
  - type: web
    name: labshare-backend
    env: python
    buildCommand: |
      # 1️⃣ Install backend dependencies
      pip install -r requirements.txt
      
      # 2️⃣ Build the frontend (Vite)
      cd labshare/labshare-connect/frontend
      npm install
      npm run build

      # 3️⃣ Safety check
      if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
        echo "❌ Frontend build failed — dist folder missing or empty."
        exit 1
      fi

      # 4️⃣ Copy build output to backend/static
      rm -rf ../../backend/static/*
      mkdir -p ../../backend/static
      cp -r dist/* ../../backend/static/

      # 5️⃣ Debug check — list backend/static after copy
      ls -R ../../backend/static

      # 6️⃣ Go back to root
      cd ../../..
    startCommand: gunicorn app:app
    buildFilter:
      paths:
        - labshare/labshare-connect/frontend/**
        - labshare/labshare-connect/backend/**
